src/Inputs/Typeahead.js
Issue: https://github.com/ClearC2/bleu/issues/6615
API Required: https://github.com/ClearC2/bleu-backend/pull/2839
=> feat(typeahead): add options for new api payload - Issue 6615

dist/es/Inputs/SearchUtils.js, src/Inputs/SearchUtils.js
I have added Fiscal Year to this list of conditions.
=> feat(report):Add fiscal year to the list

src/Inputs/SearchUtils.js
https://github.com/ClearC2/bleu/issues/7871
=> fix(conditional-predicate): fix is between for month types

src/FormBuilder.js, src/Inputs/Currency.js
Added ability to have min/max properties in currency,
property name for inputs
maxvalue
minvalue
=> feat(currency): add min/max options and validation

src/Inputs/Percentage.js
Addresses [#8486 ](https://github.com/ClearC2/bleu/issues/8486)dependent of [PR#8494 bleu](https://github.com/ClearC2/bleu/pull/8494)
=> feat(percentage): add support for 1 decimal place in percentage field

src/Inputs/ConditionalPredicate.js
Addresses [#8515-bleu-frontend](https://github.com/ClearC2/bleu/issues/8515)
References to [#7916](https://github.com/ClearC2/bleu/issues/7916)
=> feat(conditionalpredicate): allow create free form text on 'does not contain' and 'is not one of'

src/Inputs/Percentage.js
[For 8494](https://github.com/ClearC2/bleu/pull/8494)
=> feat(percentage): fix percentage field not allowing free input

src/Inputs/ConditionalInput.js, src/Inputs/SearchUtils.js
Fixes comments on [8492](https://github.com/ClearC2/bleu/pull/8492)
=> Searchutils add date field conditions

src/Inputs/ConditionalInput.js
Empty PR for semantic versioning to trigger
=> feat(searchutils): fix new conditons not showing value on conditional fields

src/QueryBuilder/Where/ConditionalTable/ConditionalTableContainer.js
SPRINT 68
Addresses [#8605](https://github.com/ClearC2/bleu/issues/8605)
=> fix(conditionaltable): fix undefined on multiple empty conditions

src/Inputs/Date/DateInput.js
Addresses [#8609 in bleu-frontend](https://github.com/ClearC2/bleu/issues/8609)
=> fix(dateinput): allow dateinput to be blanked

dist/es/QueryBuilder/Utils.js, src/QueryBuilder/Utils.js
TextAreas now have the same conditions dialog that inputs use.
=> feat(queryBuilder): add conditions filter functionality to textareas

dist/es/Inputs/Multiselect.js, dist/es/utils.js, src/Inputs/Multiselect.js, src/utils.js
- Ref: https://github.com/ClearC2/bleu/issues/8849
=> feat(multiSelect): require flag to remove invalid values

src/Inputs/Select/Select.js
This PR adds the ability to pass an onBlur prop to the Select input that returns the onBlur event.
=> feat(Select): add onBlur prop to select input type that returns onBlur event

dist/es/Inputs/ConditionalPredicate.js, src/Inputs/ConditionalPredicate.js
Ref: https://github.com/ClearC2/bleu/issues/9224
=> feat(conditionalpredicate): remove unnecessary if clause

src/Inputs/Phone.js, webpack/babel.production.js
- **build: remove webpack overlay**
- **fix(phone): prepend + for non-us numbers to trigger formatting**
=> fix(phone): prepend + for non-us numbers to trigger formatting

dist/es/Inputs/Date/DatePicker.js, src/Inputs/Date/DatePicker.js
Peggs requested dynamic values like "today" and "this month" for min and max values. Figured others would like to have a similar option. Can also set a specific number of days from "today".
=> feat(datepicker): add dynamic value options to minDate and maxDate

src/QueryBuilder/Where/ConditionalTable/ConditionalTableContainer.js
https://github.com/ClearC2/bleu/issues/10116
=> fix(reporting): is between date filters

src/Inputs/SearchUtils.js
https://github.com/ClearC2/bleu/issues/10663
=> feat(reporting): date filters

dist/es/Inputs/Percentage.js, src/Inputs/Percentage.js
Ref: https://github.com/ClearC2/bleu/issues/10673
=> fix(percentage): format value for percentage input with decimal prop

src/FormBuilder.js
https://github.com/ClearC2/bleu/issues/10768
=> feat(regex-pattern): test field for regex pattern on validate

src/QueryBuilder/Where/ConditionalTable/ConditionalTableContainer.js
Reference: https://github.com/ClearC2/bleu/issues/4756
=> fix(querybuilder): default type to input if none provided

dist/es/Inputs/Input.js, dist/es/Inputs/core/InnerCell.js, dist/es/Inputs/core/InputContainer.js, src/Inputs/Input.js, src/Inputs/core/InnerCell.js, src/Inputs/core/InputContainer.js
Reference: https://github.com/ClearC2/bleu/issues/10036
=> feat(input): hide tooltip if validation warning triggered

dist/es/QueryBuilder/Where/ConditionalTable/ConditionalTableContainer.js, src/QueryBuilder/Where/ConditionalTable/ConditionalTableContainer.js
Reference: https://github.com/ClearC2/bleu/issues/11151
=> fix(reporting): make convertSingleField return immutable Map

src/Inputs/Date/DateInput.js
https://github.com/ClearC2/bleu/issues/7088
=> fix(date-picker-blur): fix picker closing on first date selection

src/Inputs/Date/DateInput.js
Reverts ClearC2/grid-form-builder#256
=> Revert "fix(date-picker-blur): fix picker closing on first date selection"

dist/es/Inputs/Multiselect.js, src/styles/grid-form-builder.css
Reference: https://github.com/ClearC2/bleu/issues/3844
=> feat(multi-input): move cursor caret to top of input
